classes:
  rev::spark::AbsoluteEncoderConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    methods:
      AbsoluteEncoderConfig:
      Apply:
      SetSparkMaxDataPortConfig:
      Inverted:
      PositionConversionFactor:
      VelocityConversionFactor:
      ZeroOffset:
      AverageDepth:
      StartPulseUs:
      EndPulseUs:
      ZeroCentered:
  rev::spark::AbsoluteEncoderConfig::Presets:
    methods:
      REV_ThroughBoreEncoder:
      REV_ThroughBoreEncoderV2:
      REV_SplineEncoder:
