classes:
  rev::spark::AbsoluteEncoderConfigAccessor:
    methods:
      GetInverted:
      GetPositionConversionFactor:
      GetVelocityConversionFactor:
      GetAverageDepth:
      GetStartPulseUs:
      GetEndPulseUs:
      GetZeroOffset:
