classes:
  rev::spark::AlternateEncoderConfigAccessor:
    methods:
      GetCountsPerRevolution:
      GetInverted:
      GetPositionConversionFactor:
      GetVelocityConversionFactor:
      GetMeasurementPeriod:
