classes:
  rev::spark::AlternateEncoderConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    enums:
      Type:
    methods:
      FromId:
      AlternateEncoderConfig:
      Apply:
      SetSparkMaxDataPortConfig:
      CountsPerRevolution:
      Inverted:
      PositionConversionFactor:
      VelocityConversionFactor:
      AverageDepth:
      MeasurementPeriod:
  rev::spark::AlternateEncoderConfig::Presets:
    methods:
      REV_ThroughBoreEncoder:
      REV_ThroughBoreEncoderV2:
      REV_SplineEncoder:
