classes:
  rev::spark::ClosedLoopConfigAccessor:
    attributes:
      maxMotion:
      feedForward:
    methods:
      GetP:
      GetI:
      GetD:
      GetFF:
      GetDFilter:
      GetIZone:
      GetMinOutput:
      GetMaxOutput:
      GetMaxIAccumulation:
      GetPositionWrappingEnabled:
      GetPositionWrappingMinInput:
      GetPositionWrappingMaxInput:
      GetFeedbackSensor:
      GetAllowedClosedLoopError:
