classes:
  rev::detached::DetachedEncoderConfigAccessor:
    methods:
      GetInverted:
      GetPositionConversionFactor:
      GetVelocityConversionFactor:
      GetVelocityAverageDepth:
      GetAngleConversionFactor:
      GetZeroOffset:
      GetZeroCentered:
      GetStartPulseUs:
      GetEndPulseUs:
      GetAbsolutePeriodUs:
    attributes:
      signals:
