classes:
  rev::detached::SignalsConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    methods:
      SignalsConfig:
      Apply:
      EncoderPositionPeriodMs:
      EncoderVelocityPeriodMs:
      EncoderAnglePeriodMs:
