classes:
  rev::detached::DetachedEncoderConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    attributes:
      signals:
    methods:
      DetachedEncoderConfig:
      Apply:
        overloads:
          DetachedEncoderConfig&:
          SignalsConfig&:
      Inverted:
      VelocityConversionFactor:
      VelocityAverageDepth:
      PositionConversionFactor:
      AngleConversionFactor:
      ZeroOffset:
      ZeroCentered:
      StartPulseUs:
      EndPulseUs:
      AbsolutePeriodUs:
      Flatten:
