classes:
  rev::detached::SignalsConfigAccessor:
    rename: DetachedSignalsConfigAccessor
    methods:
      GetEncoderPositionPeriodMs:
      GetEncoderVelocityPeriodMs:
      GetEncoderAnglePeriodMs:
