classes:
  rev::detached::DetachedEncoderConfigAccessor:
    methods:
      GetInverted:
      GetPositionConversionFactor:
      GetVelocityConversionFactor:
      GetVelocityAverageDepth:
      GetAngleConversionFactor:
      GetZeroOffset:
      GetZeroCentered:
