classes:
  rev::spark::EncoderConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    methods:
      EncoderConfig:
      Apply:
      CountsPerRevolution:
      Inverted:
      PositionConversionFactor:
      VelocityConversionFactor:
      QuadratureAverageDepth:
      QuadratureMeasurementPeriod:
      UvwAverageDepth:
      UvwMeasurementPeriod:
  rev::spark::EncoderConfig::Presets:
    methods:
      REV_ThroughBoreEncoder:
      REV_ThroughBoreEncoderV2:
      REV_SplineEncoder:
