classes:
  rev::spark::EncoderConfigAccessor:
    methods:
      GetCountsPerRevolution:
      GetInverted:
      GetPositionConversionFactor:
      GetVelocityConversionFactor:
      GetQuadratureAverageDepth:
      GetQuadratureMeasurementPeriod:
      GetUvwAverageDepth:
      GetUvwMeasurementPeriod:
