classes:
  rev::spark::ExternalEncoderConfigAccessor:
    methods:
      GetCountsPerRevolution:
      GetInverted:
      GetPositionConversionFactor:
      GetVelocityConversionFactor:
      GetAverageDepth:
      GetMeasurementPeriod:
