classes:
  rev::spark::ExternalEncoderConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    enums:
      Type:
    methods:
      FromId:
      ExternalEncoderConfig:
      Apply:
      CountsPerRevolution:
      Inverted:
      PositionConversionFactor:
      VelocityConversionFactor:
      AverageDepth:
      MeasurementPeriod:
  rev::spark::ExternalEncoderConfig::Presets:
    methods:
      REV_ThroughBoreEncoder:
      REV_ThroughBoreEncoderV2:
      REV_SplineEncoder:
