classes:
  rev::spark::LimitSwitchConfigAccessor:
    methods:
      GetForwardLimitSwitchEnabled:
      GetForwardSwitchType:
      GetReverseLimitSwitchEnabled:
      GetReverseSwitchType:
      GetForwardLimitSwitchTriggerBehavior:
      GetForwardLimitSwitchPosition:
      GetReverseLimitSwitchTriggerBehavior:
      GetReverseLimitSwitchPosition:
