classes:
  rev::spark::LimitSwitchConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    enums:
      Type:
      Behavior:
    methods:
      LimitSwitchConfig:
      Apply:
      SetSparkMaxDataPortConfig:
      ForwardLimitSwitchEnabled:
      ForwardLimitSwitchType:
      ReverseLimitSwitchEnabled:
      ReverseLimitSwitchType:
      ForwardLimitSwitchTriggerBehavior:
      ForwardLimitSwitchPosition:
      ReverseLimitSwitchTriggerBehavior:
      ReverseLimitSwitchPosition:
      LimitSwitchPositionSensor:
