classes:
  rev::spark::MAXMotionConfigAccessor:
    methods:
      GetMaxVelocity:
      GetMaxAcceleration:
      GetAllowedClosedLoopError:
      GetPositionMode:
      GetCruiseVelocity:
      GetAllowedProfileError:
