classes:
  rev::spark::SignalsConfigAccessor:
    methods:
      GetAppliedOutputPeriodMs:
      GetAppliedOutputAlwaysOn:
      GetBusVoltagePeriodMs:
      GetBusVoltageAlwaysOn:
      GetOutputCurrentPeriodMs:
      GetOutputCurrentAlwaysOn:
      GetMotorTemperaturePeriodMs:
      GetMotorTemperatureAlwaysOn:
      GetLimitsPeriodMs:
      GetLimitsAlwaysOn:
      GetFaultsPeriodMs:
      GetFaultsAlwaysOn:
      GetWarningsPeriodMs:
      GetWarningsAlwaysOn:
      GetPrimaryEncoderVelocityPeriodMs:
      GetPrimaryEncoderVelocityAlwaysOn:
      GetPrimaryEncoderPositionPeriodMs:
      GetPrimaryEncoderPositionAlwaysOn:
      GetAnalogVoltagePeriodMs:
      GetAnalogVoltageAlwaysOn:
      GetAnalogVelocityPeriodMs:
      GetAnalogVelocityAlwaysOn:
      GetAnalogPositionPeriodMs:
      GetAnalogPositionAlwaysOn:
      GetExternalOrAltEncoderVelocityPeriodMs:
      GetExternalOrAltEncoderVelocityAlwaysOn:
      GetExternalOrAltEncoderPositionPeriodMs:
      GetExternalOrAltEncoderPositionAlwaysOn:
      GetAbsoluteEncoderVelocityPeriodMs:
      GetAbsoluteEncoderVelocityAlwaysOn:
      GetAbsoluteEncoderPositionPeriodMs:
      GetAbsoluteEncoderPositionAlwaysOn:
      GetIAccumulationPeriodMs:
      GetIAccumulationAlwaysOn:
      GetSetpointPeriodMs:
      GetSetpointAlwaysOn:
      GetIsAtSetpointPeriodMs:
      GetIsAtSetpointAlwaysOn:
      GetSelectedSlotPeriodMs:
      GetSelectedSlotAlwaysOn:
      GetMAXMotionSetpointPositionPeriodMs:
      GetMAXMotionSetpointPositionAlwaysOn:
      GetMAXMotionSetpointVelocityPeriodMs:
      GetMAXMotionSetpointVelocityAlwaysOn:
