classes:
  rev::spark::SoftLimitConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    methods:
      SoftLimitConfig:
      Apply:
      ForwardSoftLimit:
      ForwardSoftLimitEnabled:
      ReverseSoftLimit:
      ReverseSoftLimitEnabled:
