extra_includes:
- sparkbaseconfig_apply.h

classes:
  rev::spark::SparkFlexConfig:
    force_no_trampoline: true
    attributes:
      externalEncoder:
    methods:
      SparkFlexConfig:
      Apply:
        overloads:
          SparkBaseConfig&:
          SparkFlexConfig&:
          ExternalEncoderConfig&:
      Flatten:
inline_code: |
  bind_sparkbaseconfig_apply<SparkFlexConfig, decltype(cls_SparkFlexConfig)>(cls_SparkFlexConfig);

