classes:
  rev::spark::SparkBaseConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    attributes:
      absoluteEncoder:
      analogSensor:
      closedLoop:
      encoder:
      limitSwitch:
      signals:
      softLimit:
    enums:
      IdleMode:
    methods:
      SparkBaseConfig:
      Apply:
        overloads:
          SparkBaseConfig&:
          AbsoluteEncoderConfig&:
          AnalogSensorConfig&:
          EncoderConfig&:
          LimitSwitchConfig&:
          SoftLimitConfig&:
          ClosedLoopConfig&:
          SignalsConfig&:
      SetIdleMode:
      Inverted:
      SmartCurrentLimit:
      SecondaryCurrentLimit:
      AdvanceCommutation:
      OpenLoopRampRate:
      ClosedLoopRampRate:
      VoltageCompensation:
      DisableVoltageCompensation:
      Follow:
        overloads:
          int, bool:
          SparkBase&, bool:
      DisableFollowerMode:
      Flatten:
  rev::spark::SparkBaseConfig::Presets:
    methods:
      REV_NEO:
      REV_NEO_2:
      REV_NEO_550:
      REV_Vortex:
      CTRE_Minion:
