classes:
  rev::spark::SparkBaseConfigAccessor:
    attributes:
      absoluteEncoder:
      analogSensor:
      closedLoop:
      encoder:
      limitSwitch:
      signals:
      softLimit:
    methods:
      GetIdleMode:
      GetInverted:
      GetSmartCurrentLimit:
      GetSmartCurrentFreeLimit:
      GetSmartCurrentRPMLimit:
      GetSecondaryCurrentLimit:
      GetSecondaryCurrentLimitChopCycles:
      GetAdvanceCommutation:
      GetOpenLoopRampRate:
      GetClosedLoopRampRate:
      GetVoltageCompensation:
      GetVoltageCompensationEnabled:
      GetFollowerModeLeaderId:
      GetFollowerModeInverted:
